### ISSUE TITLE
Type : Lighting 1 virtual/dummy switches aren't switching

### ISSUE THREAD

**Issue by salemxp** [hansworst24/Ticz#10]

**Comment by hansworst24** [comment]
@salemxp 
can you explain a bit more what you're experiencing ? I have plenty of virtual devices, and they are working fine.
- please provide the output of /json.htm?type=devices&rid=IDX of one of the devices that does not switch, where IDX is the idx of the device (see https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s#Retrieve_status_of_specific_device for details)
- Domoticz version you're running
- Any error messages that are shown ?

**Comment by salemxp** [comment]
Domoticz v3.4834 on a raspberry pi, there's no error messages, the devices
don't switch it's all.

Here's the json outpout of one of my virtual devices : {

   "ActTime" : 1458391249,
   "ServerTime" : "2016-03-19 13:40:49",
   "Sunrise" : "06:34",
   "Sunset" : "18:39",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 10,
         "Data" : "On",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 6,
         "HardwareName" : "Presence",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : false,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "65",
         "Image" : "Fireplace",
         "IsSubDevice" : false,
         "LastUpdate" : "2016-03-19 08:30:01",
         "Level" : 0,
         "LevelInt" : 0,
         "MaxDimLevel" : 0,
         "Name" : "calendrier chauffage",
         "Notifications" : "false",
         "PlanID" : "2",
         "PlanIDs" : [ 2 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "On",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "X10",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "true",
         "Type" : "Lighting 1",
         "TypeImg" : "lightbulb",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "28"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

Your app is really cool thx

2016-03-19 10:01 GMT+01:00 hansworst24 notifications@github.com:

**Comment by hansworst24** [comment]
Thanks :)

I think I see the issue : My Dummy switches were of type "Lighting 2", and yours are "Type" : "Lighting 1", I will include this type as switchable device, test, and upload an update to the store !

**Comment by hansworst24** [comment]
OK, new version is submitted to the Store ; Probably takes a couple of hours before you will see it. I've tested the patch and seems to work fine now, hence I'll close the issue. Reach out to me if you still have problems !

Thanks
