### ISSUE TITLE
Scenes are not displayed in my windows phone

### ISSUE THREAD

**Issue by Tixav** [hansworst24/Ticz#11]
I have waiting for V1.7.1  before writing (same with V1.7).

I have 6 scenes on my domoticz.
I have one scene attached to a plan
-> the scene is displayed on ticz (computer Windows 10) when I select the good plan
-> the scene is not displayed on ticz (windows phone 10 ) when I select the same plan

To be sure I created a dedicated plan in which I attached 2 scenes
-> the both scenes are displayed on ticz (computer Windows 10) when I select this dedicated plan
-> the both scenes are not displayed on ticz (windows phone 10 ) when I select the dedicated plan

At the same time, I would like to congratulate you because Ticz a very good app. I took a look in the source code (I have bit of skill programming, but not your level) and I saw an high programming quality code !!!

PS  : I am the only one guy who wrote a comment on the windows store

**Comment by hansworst24** [comment]
Hi @Tixav  !

Thanks for your feedback, it's always nice to hear people appreciate the work :) 

Out of my head; the only logical explanation I can think of right now, is that on the Windows 10 Phone, you might have selected "Only show Favourites" in Settings--> General, where on Windows 10 PC you might have this not selected. The code for Windows 10 and Windows 10 Phone is exactly the same, so that should be the cause...... but who knows :) Can you check those parameters ?

**Comment by Tixav** [comment]
Oups.....You are right !
Sorry for the inconvenience

**Comment by hansworst24** [comment]
@Tixav 
Not a problem at all :) Apart from that, do all devices work properly for you and show up with a good icon ?

**Comment by Tixav** [comment]
Yes, except color bulb
In domoticz color bulb is divided into 2 devices, Brightness and RGBW dimmer, in ticz I see this
![capture](https://cloud.githubusercontent.com/assets/17889406/14038282/d1280b5a-f24e-11e5-978a-b0a325e40cf1.PNG)

SalonLampeLuminosité (brightness) is normally a dimmer, and impossible to control % from Ticz
SalonLampColors (Hue) is normally RGBW dimmer and I control Brightness from ticz
see capture of the devices in domoticz bleow
![capture1](https://cloud.githubusercontent.com/assets/17889406/14038336/8eabe5e8-f24f-11e5-8f83-2be9461d9fdd.PNG)
![capture2](https://cloud.githubusercontent.com/assets/17889406/14038337/8ead43e8-f24f-11e5-8537-5ea587e97bd5.PNG)

**Comment by hansworst24** [comment]
Ok, I'll look into that. I admit I havent looked at RGB dimmers a lot, so that will need some work ☺

**Comment by hansworst24** [comment]
@Tixav 

I'm looking into the RGBW Dimmers and might need your feedback in order to test things properly.

I basically fixed your SalonLampeLuminosité , and implemented a color picker for RGBW and RGB Dimmer..... The RGB-Dimmer sends the HEX value of the selected color back to Domoticz, but how can you process it from there ?

I have a Philips Hue lamp to test, but in lua there is no way to get to the actual RGB values of the RGB Dimmer.... ?

**Comment by Tixav** [comment]
Hello Hansworst,
I own an Aeotec Color LED Bulb (Zwave)
![aeotec](https://cloud.githubusercontent.com/assets/17889406/15157738/2e28c4bc-16ed-11e6-8a13-cc9c5169c4a7.PNG)
And I agree, currently there is no way to get the actual RGB value of the Bulb (I tried to get directly from openzwave but it is very slow, so incompatible with my applications)
So I found a trick, for one month I use a selector switch that I set up like this
![selector](https://cloud.githubusercontent.com/assets/17889406/15158186/edf4c51a-16ee-11e6-8e37-c2ea63a53082.PNG)
Then I wrote in LUA script :
`  
xchangename=next(devicechanged)
    xchangeval=tostring(devicechanged[xchangename])

```
commandArray = {}

-- Color & Brignhtness definition for each button of selector switch
if ( xchangename == 'RGBW' ) then

    if (xchangeval=="Off")              then 
        color="19"
        brightness="0"
    end

    if (xchangeval=="Color_BienEtre")   then 
        color="19"
        brightness="20"
    end

    if (xchangeval=="Color_Courrier")   then 
        color="296" 
        brightness="20"
    end

    if (xchangeval=="Color_Sonnette")   then 
        color="236" 
        brightness="100"
    end

    if (xchangeval=="Color_Portail")    then 
        color="113"
        brightness="50"
    end

    --control of the device RGBW (SalonLampColors -> English : SittingroomColorBulb ) by JSON
    uu="http://localhost:8080/json.htm?type=command&param=setcolbrightnessvalue&idx=250&hue="..color.."&brightness="..brightness.."&iswhite=false"
    commandArray['OpenURL']=uu 
end

------------------BELOW ALL EVENT THAT CONTROL EACH COLOR SO EACH BUTTON OF THE SELECTOR
Off="Set Level 0"
Color_BienEtre="Set Level: 10"
Color_Courrier="Set Level: 20"
Color_Sonnette="Set Level: 30"
Color_Portail="Set Level: 40"

    --LETTERBOX
        -- courrier is in the letter box and alarme disable and not night
        if ( devicechanged['Courrier'] == 'On' and otherdevices['Alarme'] == 'Off' and otherdevices['FoscamNuit'] == 'Off' ) then

            --memorizing current color such as "Set Level: 10" "Set Level: 20" "Set Level: 30" "Set Level: 40"
            commandArray['Variable:ColorBefore']= otherdevices_svalues['RGBW']

            --control the color bulb with correct value defined in the biggining of the file
            commandArray['RGBW']=Color_Courrier
        end

        -- courrier pris is remove of the letter box then set the bulb with the memorizing value before the event
        if ( devicechanged['Courrier'] == 'Off' and not (otherdevices['RGBW'] == 'Off' )  ) then commandArray['RGBW']='Set Level: '..uservariables['ColorBefore'] end

    --BELL
        -- sonnette : bell
        if ( devicechanged['Sonnette'] == 'On' and time.hour < 21 ) then
            if ( otherdevices['Alarme'] == 'Off' ) then
                os.execute ("/home/pi/domoticz/Sons/PlaySound.sh /home/pi/domoticz/Sons/sonnette.mp3 &")
                Avant= otherdevices_svalues['RGBW']
                commandArray[1]={['RGBW']=Color_Sonnette}
                commandArray[2]={['RGBW']='Set Level: '..Avant..' AFTER 30'}
            end
            SmS("Sonnette", "Sonnette ACTIVE","True","script_device_sonette.lua")
        end

    --GATE
        -- portail ouvert et pas alarme (on est a la maison) : Gate opened and alarm Off
        if ( devicechanged['Portail_Etat'] == 'On' and otherdevices['Alarme'] == 'Off' ) then
            commandArray['Variable:ColorBefore']= otherdevices_svalues['RGBW']
            commandArray['RGBW']=Color_Portail
        end

        -- portail fermee : Gate closed
        if ( devicechanged['Portail_Etat'] == 'Off' ) then
            --on reset à la fermeture du portail sauf si Color_BienEtre
            if ( commandArray['Variable:ColorBefore']=="10" ) then
                commandArray['RGBW']='Set Level: 10'
            else
                commandArray['RGBW']='Set Level: 0'
            end
        end


return commandArray`
```

**Comment by Tixav** [comment]
I hope that will help you

**Comment by hansworst24** [comment]
Thanks, I see the logic behind it, but it doesn't yet provide a good way to use the colorpicker to set a lightbulb to any color. I read somewhere that the Domoticz guys will look into good RGB support in v4.x, so I think we have to wait for that, to make full use of our RGB bulbs :smile:
