### ISSUE TITLE
REQ: BWR102 Bathroom scale device

### ISSUE THREAD

**Issue by keptenkurk** [hansworst24/Ticz#13]
To start with: thanks for this great app an all the work! Switching is instantaneous, never saw that on any other device!
I have a bathroom scale device of type BWR102 which doesn't show an icon nor graphs. Could you please add it to Ticz? The value is updated through an api call. No idea why it shows as smartmeter.
Device details: 

```
{
ActTime: 1460424826,
ServerTime: "2016-04-12 03:33:46",
Sunrise: "06:49",
Sunset: "20:28",
result: [
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 255,
CustomImage: 0,
Data: "60.5 kg",
Description: "",
Favorite: 1,
HardwareID: 2,
HardwareName: "Smartmeter",
HardwareType: "P1 Smart Meter USB",
HardwareTypeVal: 4,
HaveTimeout: false,
ID: "60",
LastUpdate: "2016-04-10 07:32:51",
Name: "Marina",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: "-",
SubType: "BWR102",
Timers: "false",
Type: "Weight",
TypeImg: "scale",
Unit: 4,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "57"
}
],
status: "OK",
title: "Devices"
}
```

**Comment by hansworst24** [comment]
@keptenkurk I see you've spend a lot of energy getting your scale included :) I found your wordpress site while searching for more info on the BWR102 device...

For graphs to show up, I need some test-data (sorry, I know it's personal data :) in order to check they key/name values that the graph should plot. Could you send me the outcome of : `/json.htm?type=lightlog&idx=<IDX>`, where `<IDX>` should be 57 in your case.

**Comment by keptenkurk** [comment]
The url you propose returns status: "ERR" 
I guess type=lightlog only applies to switch device types?

**Comment by hansworst24** [comment]
It is typically used for any on/off device in Domoticz. The way I use to identify what is called, is by using Fiddler, and trace which calls are being made to Domoticz in the webUI. For example, these calls are made and return json data for a temperature device

```
http://<ip>:<port>/json.htm?type=graph&sensor=counter&idx=3&range=year
http://<ip>:<port>/json.htm?type=graph&sensor=counter&idx=3&range=month
http://<ip>:<port>/json.htm?type=graph&sensor=counter&idx=3&range=day
```

In order to get your scale data, I'd recommend to install Fiddler (it's sort of a proxy server), and click on the "Log" button of your scale. At that point it should show the graph and you can stop Fiddler from capturing, and somewhere in those lines you'd see which URL is called.

Depending on your version of Domoticz it might be something new that I haven't seen before :)

![fiddler](https://cloud.githubusercontent.com/assets/7300919/14472141/06ba5db6-00f2-11e6-9218-514a33f3078e.jpg)

**Comment by keptenkurk** [comment]
Got it! Used Firefox & firebug plugin to retrieve:

/json.htm?type=graph&sensor=counter&idx=57&range=month

```
{
ValueQuantity: "",
ValueUnits: "",
result: [
{
d: "2016-03-26",
v_max: "59.0",
v_min: "59.0"
},
{
d: "2016-03-30",
v_max: "61.1",
v_min: "61.1"
},
{
d: "2016-03-31",
v_max: "60.5",
v_min: "60.5"
},
{
d: "2016-04-01",
v_max: "60.4",
v_min: "60.4"
},
{
d: "2016-04-02",
v_max: "60.4",
v_min: "60.4"
},
{
d: "2016-04-06",
v_max: "60.7",
v_min: "60.7"
},
{
d: "2016-04-10",
v_max: "60.5",
v_min: "60.5"
}
],
status: "OK",
title: "Graph counter month"
}
```

Since my watermeter has the same type of url (i.e. a counter) would that also be displayed in the same update? Or should i file a separate request for that device type :-)

**Comment by keptenkurk** [comment]
this is the day graph info:

/json.htm?type=graph&sensor=counter&idx=58&range=day

```
{
result: [
{
d: "2016-04-12 07:25",
v: "76.3"
},
{
d: "2016-04-12 07:30",
v: "76.3"
},
{
d: "2016-04-12 07:35",
v: "76.3"
},
{
d: "2016-04-12 07:40",
v: "76.3"
},
{
d: "2016-04-12 07:45",
v: "76.3"
},
{
d: "2016-04-12 07:50",
v: "76.3"
},
{
d: "2016-04-12 07:55",
v: "76.3"
},
{
d: "2016-04-12 08:00",
v: "76.3"
},
{
d: "2016-04-12 08:05",
v: "76.3"
},
{
d: "2016-04-12 08:10",
v: "76.3"
},
{
d: "2016-04-12 08:15",
v: "76.3"
},
{
d: "2016-04-12 08:20",
v: "76.3"
}
],
status: "OK",
title: "Graph counter day"
}
```

...different index: my wife didn't dare to step on the scale today ;-) ...
range=year follows the same pattern as month

**Comment by hansworst24** [comment]
OK, I added the graphs for the scale. It would look something like this. I assume that there also is a yearly graph ? If so, just to be sure, could you send the output for that as well ?

In general, the monthly and yearly data contains a `v_min` and `v_max`, and Domoticz plots an area graph showing the min and max values. For the moment I only take the `v_max` in the graphs as I couldn't get these 'average graphs' to work properly yet.

For the watermeter, I'd have to get the device-info and graph data once again :) I use the device type to identify if there are any graphs available for the device and if so, which one.. They all need different y-axis headers etc.. Preferrably, add these in a seperate request so it's nicely tracked :)

![weight](https://cloud.githubusercontent.com/assets/7300919/14484487/2d2cd672-0151-11e6-8d87-27e6c1df88ac.jpg)

**Comment by keptenkurk** [comment]
Great! Looks cool. 
Yearly data looks the same as monthly:

/json.htm?type=graph&sensor=counter&idx=58&range=year

```
{
ValueQuantity: "",
ValueUnits: "",
result: [
{
d: "2016-03-26",
v_max: "76.1",
v_min: "76.0"
},
{
d: "2016-03-28",
v_max: "76.2",
v_min: "75.7"
},
{
d: "2016-03-29",
v_max: "76.5",
v_min: "76.5"
},
{
d: "2016-03-30",
v_max: "77.0",
v_min: "77.0"
},
{
d: "2016-03-31",
v_max: "77.3",
v_min: "77.3"
},
{
d: "2016-04-01",
v_max: "76.0",
v_min: "76.0"
},
{
d: "2016-04-02",
v_max: "76.0",
v_min: "76.0"
},
{
d: "2016-04-03",
v_max: "76.9",
v_min: "76.9"
},
{
d: "2016-04-04",
v_max: "77.2",
v_min: "77.2"
},
{
d: "2016-04-05",
v_max: "76.7",
v_min: "76.7"
},
{
d: "2016-04-06",
v_max: "76.5",
v_min: "76.5"
},
{
d: "2016-04-07",
v_max: "77.3",
v_min: "77.3"
},
{
d: "2016-04-08",
v_max: "76.4",
v_min: "76.4"
},
{
d: "2016-04-09",
v_max: "77.3",
v_min: "77.3"
},
{
d: "2016-04-10",
v_max: "77.3",
v_min: "77.3"
},
{
d: "2016-04-12",
v_max: "76.3",
v_min: "76.3"
},
{
d: "2016-04-13",
v_max: "76.4",
v_min: "76.4"
}
],
status: "OK",
title: "Graph counter year"
}
```

**Comment by hansworst24** [comment]
ok, this one is implemented. I'll close it now, once in the Stor3e please check and reopen if neccesary :)

**Comment by keptenkurk** [comment]
Works like a charm! Many thanks!
