### ISSUE TITLE
Device Cresta, TFA TS34C shows 00:00 at x-axis labels of Past Month graph

### ISSUE THREAD

**Issue by keptenkurk** [hansworst24/Ticz#14]
A minor issue: 
The x-axis labels on the Past Month graph of these type of devices (possibly all combined Temp/Moisture devices?)  show "00:00" where a date was expected 
Same for ForcastIO virtual sensor of type THB1 - BTHR918, BTHGN129. Internal temp of Raspberry is ok (LaCrosse TX3).
THR128/138, THC138 type is also ok regarding x-axis but graps: Past Year - Past 24Hr, Past Month, Past Year ( so Past Year graph appears twice)
Device info of TS34C device:

```
{
ActTime: 1460425775,
ServerTime: "2016-04-12 03:49:35",
Sunrise: "06:49",
Sunset: "20:28",
result: [
{
AddjMulti: 1,
AddjMulti2: 1,
AddjValue: 0,
AddjValue2: 0,
BatteryLevel: 100,
CustomImage: 0,
Data: "12.9 C, 67 %",
Description: "",
DewPoint: "6.92",
Favorite: 1,
HardwareID: 3,
HardwareName: "RFXCOM",
HardwareType: "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
HardwareTypeVal: 1,
HaveTimeout: false,
Humidity: 67,
HumidityStatus: "Comfortable",
ID: "3B0E",
LastUpdate: "2016-04-12 03:48:34",
Name: "Veranda",
Notifications: "false",
PlanID: "0",
PlanIDs: [
0
],
Protected: false,
ShowNotifications: true,
SignalLevel: 6,
SubType: "Cresta, TFA TS34C",
Temp: 12.9,
Timers: "false",
Type: "Temp + Humidity",
TypeImg: "temperature",
Unit: 1,
Used: 1,
XOffset: "0",
YOffset: "0",
idx: "7"
}
],
status: "OK",
title: "Devices"
}
```

**Comment by hansworst24** [comment]
@keptenkurk 
Thanks for the feedback :) Always nice to hear the work is appreciated !

I fixed the monthly scale for Temperature + Humidity graphs, but am a bit confused on which device shows the Year graph twice.. ?

I assume that the TS34C device was the one with the wrong Monthly scale. If that is true, could you provide the device info for the THR128/138 please ? That will help me in identifying why it is showing the Year grap twice !

**Comment by keptenkurk** [comment]
Sorry for the mixup:
LaCrosse TX3:  All ok (like Raspberry internal temp)
TFA TS34C :  00:00 on x-axis of monthly graph  
THB1 - BTHR918, BTHGN129: 00:00 on x-axis of monthly graph  (ForecastIO temp graph)
THR128/138: All ok (virtual temp device i use.). Not been able to reproduce the extra Past Year graph on this device so forget about that...

**Comment by hansworst24** [comment]
ok, then I think I got it sorted :) Once I get your scale graphs included, I'll upload a new version to the Windows Store. For now I'll close this issue

**Comment by keptenkurk** [comment]
Great job! Thanks.
