### ISSUE TITLE
https options

### ISSUE THREAD

**Issue by Tixav** [hansworst24/Ticz#16]
Do you forecast to add https option ?

**Comment by hansworst24** [comment]
@Tixav 

Wasn't forecasted but has been implemented now :smile: . Need to tweak a few final things before releasing updated version to the Store.

**Comment by Tixav** [comment]
Great, It is working well ! (but domoticz icons are not displayed : black area instead )

Thanks !

**Comment by hansworst24** [comment]
Hmm, which version of Domoticz are you running ? Do the internal Ticz icons get displayed properly ? Im in the process of upgrading my own setup from 2.4x to 3.x and will have a look at how the Domoticz icons behave once Ive migrated over,I personally like the Ticz icons more :)

**Comment by Tixav** [comment]
I am using Domoticz V 3.5111 (beta). The internal icons are well displayed. 
The domoticz icons are not displayed only if I select HTTPS options (Windows phone or computer)

**Comment by hansworst24** [comment]
Ahh, got it ! Then I missed a few URLs here and there :) I'll correct and push a new version to the store !

**Comment by hansworst24** [comment]
new version is pushed to the Store !

**Comment by Tixav** [comment]
Yes, It is working like a charm in https mode. Thanks a lot.
Just a question, why you do not show Ticz app in the domoticz forum (https://www.domoticz.com/forum/viewforum.php?f=21). Perhaps, people could help you for develloping...(Cameras view, Color bulb...I do not know what more)

**Comment by hansworst24** [comment]
Cool, you're welcome 😄 

yeah, I probably should do some advertisement. I'll create a topic tomorrow, thanks for the tip and the right place to put it 👍

**Comment by Tixav** [comment]
I am still ready to help for a well built project. Good luck
