### ISSUE TITLE
Colorpicker for Hue/RGB

### ISSUE THREAD

**Issue by hansworst24** [hansworst24/Ticz#17]

**Comment by hansworst24** [comment]
The colorpicker methods  within Domoticz will be reworked entirely as they aren't really functioning in combination with i.e. lua. See https://www.domoticz.com/forum/viewtopic.php?f=6&t=10458

The groundwork for a Colorpicker in Ticz is WIP. The question is when Domoticz will be able to handle it properly / consistently

**Comment by gcoupe** [comment]
Reading the topic in the Domoticz forum, I get the impression that the rework is not high priority for the Domoticz folks. It would be good if Ticz provided a colorpicker within the app - all I can do at the moment with my Fibaro RGBW controller is turn it on or off in Ticz.

Other than that, Ticz is looking very good!

**Comment by hansworst24** [comment]
Hi ! 

Thanks for the feedback :smile: 

Basic RGB Dimmer functionality has been implemented in Ticz since version 1.8.2, and I believe it should pop-up for a Fibaro RGBW dimmer. Although only visible in Wide or Large view of your Device (i.e. choose Grid View or List View for the room), it shows a RGB picker icon.

![dimmer1](https://cloud.githubusercontent.com/assets/7300919/15352048/a196723c-1ce2-11e6-8255-130ab96feb87.jpg)

When clicked, it shows a RGB color picker and a "Set Color" button. 
![dimmer2](https://cloud.githubusercontent.com/assets/7300919/15352053/abe6c192-1ce2-11e6-8361-b4fbe0c19daf.jpg)

When clicking "Set Color", it sends the HEX value of the color to Domoticz. Sadly I cannot test what happens afterwards within Domoticz and how Domoticz treats that command, but from what I understand that's the part in Domoticz which is a bit messed up... :frowning:

**Comment by gcoupe** [comment]
Aha - that was it: I needed to choose a different view to reveal the colorpicker... Thanks!

**Comment by hansworst24** [comment]
cool :smile: Big question is : does it work properly with your RGBW Dimmer ? Cause I only send the command from Ticz, but couldn't test it..

**Comment by gcoupe** [comment]
Just tested it using Ticz on a Windows Phone (Lumia 1020). It seems to work as expected. Thanks!

**Comment by hansworst24** [comment]
perfect 👍
