### ISSUE TITLE
Fire alarm icon missing

### ISSUE THREAD

**Issue by MikaPetteriLundgren** [hansworst24/Ticz#18]
I'm using Domoticz icons in the Ticz and I do have a fire alarm device called "Palohälytin" and it's icon is not shown at all in Ticz. Attached a screen capture from my Windows Mobile 10 device. As can seen from the screen capture, there is no icon at all in "Palohälytin" device.

![wm10 screen capture](https://cloud.githubusercontent.com/assets/13355428/15269405/24b27b0a-1a06-11e6-804d-dcd034dc88a0.png)

Correct icon can be seen from screen capture taken from Domoticz web interface.

![fire alarm icon in domoticz](https://cloud.githubusercontent.com/assets/13355428/15269415/6191fdca-1a06-11e6-808e-e3cd485bcaba.png)
The fire alarm device is KD-101. Domoticz version is 3.4834 and I should have the latest version of the Ticz running in my Phone.

**Comment by hansworst24** [comment]
Hi !

Could you send me the output of http://**IP**:**PORT**/json.htm?type=devices&rid=**IDX**, with IDX being the IDX of your fire alarm ?

If possible, also please identify the filenames of the images that are used in Domoticz for the fire alarm. I don't see them in my setup, but I probably overlook it !

**Comment by MikaPetteriLundgren** [comment]
Hi,

Thanks for the prompt reply. Please find the output of JSON command below:

{
   "ActTime" : 1463253049,
   "ServerTime" : "2016-05-14 22:10:49",
   "Sunrise" : "04:48",
   "Sunset" : "21:59",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Normal",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 3,
         "HardwareName" : "RFXtrx433E",
         "HardwareType" : "RFXCOM - RFXtrx433 USB 433.92MHz Transceiver",
         "HardwareTypeVal" : 1,
         "HaveDimmer" : false,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "A27700",
         "LastUpdate" : "2016-05-12 17:17:26",
         "MaxDimLevel" : 0,
         "Name" : "Palohälytin",
         "Notifications" : "true",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : true,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Normal",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "KD101 smoke detector",
         "SwitchType" : "Smoke Detector",
         "SwitchTypeVal" : 5,
         "Timers" : "false",
         "Type" : "Security",
         "TypeImg" : "smoke",
         "Unit" : 0,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "34"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

Names of the file alarm icons are smoke48on.png and smoke48off.png. I managed to find the icons from www/images folder, so you can find the icons attached.

![smoke48off](https://cloud.githubusercontent.com/assets/13355428/15270269/1dda4364-1a22-11e6-909f-b66680e44eb7.png)
![smoke48on](https://cloud.githubusercontent.com/assets/13355428/15270268/1dd925d8-1a22-11e6-8401-18b31cb8b0e7.png)

**Comment by hansworst24** [comment]
Thanks, now I see them too in my setup 😄. I'll add them hopefully tomorrow and push a new version to the Store and let you know !

**Comment by hansworst24** [comment]
Smoke detector implemented :smile: I'm compiling 1.8.3 now, and it will hit the Store today !

**Comment by MikaPetteriLundgren** [comment]
Icon of the smoke detector is now visible! Thanks for the good work!

**Comment by hansworst24** [comment]
no problem, thanks for making Ticz better 😄
