### ISSUE TITLE
Last user variable cannot be modified

### ISSUE THREAD

**Issue by MikaPetteriLundgren** [hansworst24/Ticz#21]
It seems that last user variable of Domoticz Variables list cannot be be modified. By default the last user variable is not visible at all. Please see a screen capture below for more information.

![last_line_hidden](https://cloud.githubusercontent.com/assets/13355428/15805068/e12a06a0-2b26-11e6-917b-68c001079e25.png)

But when pulling the list up then it's possible to see the last user variable but when finger is lifted up from the screen then the last user variable is hidden again. Please see a screen capture below for more information.

![last_line_visible](https://cloud.githubusercontent.com/assets/13355428/15805083/688af046-2b27-11e6-917f-2c44f6ef8a08.png)

In practice all user variables should be visible and modifiable by default.

**Comment by hansworst24** [comment]
OK, I think I got this fixed, but can't test it for real as the emulators do not really take into account support for the on-screen keys. I'm pushing v2.01 to the store in about 15 minutes. Let me know if it's better !

**Comment by MikaPetteriLundgren** [comment]
It's now fixed in portrait mode use cases but I noticed that in landscape mode update buttons are still partially hidden by the on-screen keys. Please see a screen capture below for more information.

![user_variables_landscape](https://cloud.githubusercontent.com/assets/13355428/15853597/72fc4074-2cae-11e6-993a-635a4750baf0.png)
I also tried this with Windows 10 PC and it looks like scroll bar partially hides the update buttons in this case as one can see from the screen capture below.

![user_variables_landscape_pc](https://cloud.githubusercontent.com/assets/13355428/15853666/b0d7f30c-2cae-11e6-8af0-9c7ad1948e74.png)
I'm not sure how often people use mobile phones in landscapre orientation so I can't say is this something that needs to be fixed or not.

Thanks a lot from the great support!

**Comment by hansworst24** [comment]
Hi !

Based on the first screenshot, i think that is still an old version as I see the Variable name doesnt get the full width of the control. Are you sure that screenshot is from the latest version 2.0.1.0 ?

The second screenshot is valid, I think I just make the vertical scrollbar hidden, who needs them...? :)

Btw the version info should be visible as well now, in the STAR menu option :) bottom-left corner

**Comment by MikaPetteriLundgren** [comment]
It's correct that the first screenshot seems to be from old version... ;-( It looks like I've attached a wrong screenshot, sorry about that. Please find a correct screenshot below:

![landscape_update_buttons_hidden](https://cloud.githubusercontent.com/assets/13355428/15870779/2147ba78-2cfa-11e6-965f-bdee8e4a8291.png)
I'm not sure does anyone really need vertical scroll bar in this context but of course it could be difficult for some users to understand the list continues if no vertical scroll bar is visible...

Version information is now working perfectly in both orientations. Great work!

**Comment by hansworst24** [comment]
Thanks 😄 I was hoping that with a screenshot of the latest version, the soft-buttons wouldn't cover part of the Update buttons 😃 . The changes I made _should_  have fixed that...

What kind of phone are you running Ticz on ? 

I've seen some reports related to certain Lumia's having soft-buttons that auto-hide, and therefore the app doesn't know what the "VisibleBounds" truly are....But then again...if everything works fine in portrait-mode it should work...

What I'll do for now is to stretch the Update button a bit more, so you'll have more luck in hitting the button 😄

**Comment by hansworst24** [comment]
maybe worth checking ; do you see the same behavior (part of the screen disappearing behind the soft-buttons) for example when you open up Graphs for a Device (long tap a device, Show Graphs) ?

**Comment by MikaPetteriLundgren** [comment]
I'm running Ticz on Lumia 950 (OS version: 10.0.10586.318). Behaviour is similar in Graphs view so soft keys do hide a part of the graph in landscape orientation. I noticed that Ticz organizes the device icons differently depending are the soft keys visibile or not (see screen captures below). I don't know but could this help you about understanding what could be the root cause for this kind of behaviour...

I agree that stretching the update buttons a bit fixes an issue regarding to variables list.

![landscape_soft_keys_visible](https://cloud.githubusercontent.com/assets/13355428/15890695/81a26272-2d79-11e6-8012-e1bfe807c6c7.png)

![landscape_soft_keys_not_visible](https://cloud.githubusercontent.com/assets/13355428/15890700/8944092c-2d79-11e6-954c-0e05653fc4f2.png)

**Comment by hansworst24** [comment]
Thanks ! So I'm correct to deduct that the 950 can hide/show the navigation soft-buttons  on the display, right ? I believe you can swipe from the bottom to show them, and again to hide them ?

If so, it does at least explain why the soft-buttons are on top of the controls:smile: For these kind of phones it's tricky to get the exact boundaries which are visible to the user. I'll need to have a loot to see if I can detect if the soft-buttons are shown or hidden, and then make adjustments to the layout accordingly... The next few days I'll be busy with some other things, but I'll have a look once I'm back :smile:

**Comment by MikaPetteriLundgren** [comment]
Yes, it's correct that one is able hide/show soft keys swiping from the bottom of the screen. I think fixing this is more like "nice to fix" than something that really needs to be fixed. But it's appreciated if you have time to look this one still... ;-)

**Comment by hansworst24** [comment]
I was able to do some test on a emulator, and on the emulator the screen resizes properly when I hide or show the soft-keys bar, at least with the latest version of Ticz (2.0.2). Does the issue still exist for you ?

**Comment by MikaPetteriLundgren** [comment]
Issue seems to be fixed now with the latest version (2.0.2). Thanks for the good work. I'll now close the case.
