### ISSUE TITLE
Error loading Domoticz Config (The text associated with this error code could not be fun. The operation timed out)

### ISSUE THREAD

**Issue by danreg** [hansworst24/Ticz#27]
Hello,

I've extended my domoticz setup with philips hue devices and logitech harmony hub. After this I cannot start Ticz again. 

I get this error:
Error loading Domoticz Config (The text associated with this error code could not be fun. The operation timed out)

Is it possible to get further information which device causes the issue?

Thanks

**Comment by danreg** [comment]
Mh after restarting my lumia everything is working again. Don't know what was wrong

**Comment by hansworst24** [comment]
@danreg happy to hear a restart helped :) Normally a "Operation timed out" is exactly what it says... the request timed out... More info of why and how isn't provided by the webclient that is used in VB.net :(

Happy to hear it's solved... As you may know ; I went to Android and the project currently is suspended ( no more development)...But honestly, Ticz is way better and nicer than what I see on Android... :)
